/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElCollapseTransition: typeof import('element-plus/lib')['ElCollapseTransition']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElRadio: typeof import('element-plus/lib')['ElRadio']
    ElRadioGroup: typeof import('element-plus/lib')['ElRadioGroup']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSlider: typeof import('element-plus/lib')['ElSlider']
    ElSwitch: typeof import('element-plus/lib')['ElSwitch']
    ElTooltip: typeof import('element-plus/lib')['ElTooltip']
  }
}
